# Generated by Django 2.0.4 on 2018-05-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('interest', models.PositiveIntegerField()),
                ('duedate', models.DateField(max_length=10)),
                ('reminddate', models.PositiveSmallIntegerField(null=True)),
                ('interestamount', models.PositiveIntegerField()),
                ('dueamount', models.PositiveIntegerField()),
                ('type', models.CharField(default='lender', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LenderPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField(null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('lenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceCorp.Lender')),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('interest', models.PositiveIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('duedate', models.DateField(max_length=10)),
                ('reminddate', models.PositiveSmallIntegerField(null=True)),
                ('interestamount', models.PositiveIntegerField()),
                ('dueamount', models.PositiveIntegerField()),
            ],
        ),
    ]
