# Generated by Django 2.0.4 on 2018-05-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceCorp', '0004_payee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayeePaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField(null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('payeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceCorp.Payee')),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
